#**1.DATAFRAME**

##**Pandas DataFrame**

##**Pandas**

Pandas adalah Library analisis data yang memiliki struktur data yang diperlukan untuk membersihkan data mentah ke dalam sebuah bentuk yang cocok untuk analisis(yaitu tabel).

Pandas melkaukan tugas penting seperti menyelaraskan data untuk perbandingan dan penggabungan set data, penanganan data yang hilang, dll.

##Import Modul

In [5]:
import pandas as pd

##Membuat DataFrame

**Membuat Matriks Menggunakan List**

In [5]:
# List
list_buahku = ['Jeruk', 'Pepaya', 'Mangga', 'Rambutan', 'Leci', 'Nanas', 'Manggis']
# Membuat DataFrame menggunakan list_buahku
df = pd.DataFrame(list_buahku)
df


0
0     Jeruk
1    Pepaya
2    Mangga
3  Rambutan
4      Leci
5     Nanas
6   Manggis

**Membuat Data Frame Menggunakan List dan Fungsi Zip**

In [ ]:
#Membuat data frame dengan list
list_buah = ['Jeruk', 'Pepaya', 'Mangga', 'Rambutan']
df = pd.DataFrame(list_buah)
df

0
0  Mangga
1   Nanas
2  Anggur
3   Jeruk

In [7]:
#Membuat data frame menggunakan list dan fungsi zip
list_buah = ['Mangga', 'Nanas', 'Anggur',' Jeruk']
#list berat buah(integer)
list_berat = [10, 20, 40, 30]

df = pd.DataFrame(list(zip(list_buah, list_berat)),
                  columns = ['Nama Buah', 'Banyak Buah'])
df

Nama Buah  Banyak Buah
0    Mangga           10
1     Nanas           20
2    Anggur           40
3     Jeruk           30

**Membuat Data Frame Menggunakan List Multidimensi**

In [8]:
# Membuat Data Frame menggunakan List Multidimensi
list = [['Shintya', 17], ['Rachma', 18],
        ['Yulista', 19], ['Dewi', 20]]
df = pd.DataFrame(list, columns = ['Nama', 'Umur'])
df

Nama  Umur
0  Shintya    17
1   Rachma    18
2  Yulista    19
3     Dewi    20

**Membuat Data Frame Menggunakan Dictionary**

Menggunakan input dictionary merupakan cara yang paling mudah dalam membuat dataframe. Key akan menjadi nama kolom dan valuenya akan menjadi data dalam kolom tersebut(biasanya berupa list).Strukturnya sebagai berikut :
```
data = {'Nama Kolom 1' : ['Data Baris 1', 'Data Baris 2', ...],
        'Nama Kolom 2' : ['Data Baris 1', 'Data Baris 2', ...],
        ...
        }
df = pd.DataFrame (data)
```

In [ ]:
# Membuat Data Frame menggunakan dictionary
Laptop = {'Type Laptop' : ['ASUS', 'Hp', 'Lenovo', 'Huawei', 'MacbookAir'],
         'Harga (juta)' : [7, 14, 6, 8, 40]}
df = pd.DataFrame(Laptop)
df

Type Laptop  Harga (juta)
0        ASUS             7
1          Hp            14
2      Lenovo             6
3      Huawei             8
4  MacbookAir            40

##Mengimport DataFrame

Kamu dapat mengimpor dataframe dari le berupa tabel lainnya seperti .xls, .xlsx, .csv, .txt, dan .json.


###Import DataFrame dari File CSV

In [6]:
# Membuat Data Frame dari import Data

## Data CSV
data = pd.read_csv('/content/SampleSuperstore.csv')
data.head()

Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164

In [10]:
data = pd.read_csv('/content/SampleSuperstore.csv')
data.head(8)

Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
5  Standard Class   Consumer  United States      Los Angeles  California   
6  Standard Class   Consumer  United States      Los Angeles  California   
7  Standard Class   Consumer  United States      Los Angeles  California   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   
5        90032   West        Furniture  Furnishings   48.8600         7   
6        90032   West  Office Supplies          Art    7.2800         4   
7        90032   West       Technology       Phones  907.1520         6   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  
5      0.00   14.1694  
6      0.00    1.9656  
7      0.20   90.7152

###Import DataFrame dari File Excell

In [20]:
## Data Excel
data1 = pd.read_excel('/content/datasetpilkadadki.xlsx')
data1.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

##DataFrame & Series

Di pandas terdapat 2 kelas data baru yang digunakan sebagai struktur dari spreadsheet:
1. **Series**

2. **DataFrame**



In [12]:
#Series
number_series = pd.Series([1,2,3,4,5,5])
print("Series : ")
number_series

Series : 


0    1
1    2
2    3
3    4
4    5
5    5
dtype: int64

Pada contoh yang diberikan, Series menggunakan library pandas.

**Series** adalah struktur data satu dimensi dalam pandas yang dapat menyimpan data homogen (data dengan tipe yang sama)

In [13]:
#DataFrame
matrix = [[1,2,3],
          ['a','b','c'],
          [3,4,5],
          ['d',4,6]]
matrix_df = pd.DataFrame(matrix)
matrix_df

0  1  2
0  1  2  3
1  a  b  c
2  3  4  5
3  d  4  6

##Atribut DataFrame & Series
Dataframe dan series memiliki sangat banyak atribut yang digunakan untuk transformasi data, tetapi ada beberapa attribute yang sering dipakai.

In [7]:
data

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

**1. Atribut .head()**

Atribut .head() untuk melihat 5(default dan bisa dirubah) data teratas pada dataframe.

In [17]:
data.head(10)

Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
5  Standard Class   Consumer  United States      Los Angeles  California   
6  Standard Class   Consumer  United States      Los Angeles  California   
7  Standard Class   Consumer  United States      Los Angeles  California   
8  Standard Class   Consumer  United States      Los Angeles  California   
9  Standard Class   Consumer  United States      Los Angeles  California   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   
5        90032   West        Furniture  Furnishings   48.8600         7   
6        90032   West  Office Supplies          Art    7.2800         4   
7        90032   West       Technology       Phones  907.1520         6   
8        90032   West  Office Supplies      Binders   18.5040         3   
9        90032   West  Office Supplies   Appliances  114.9000         5   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  
5      0.00   14.1694  
6      0.00    1.9656  
7      0.20   90.7152  
8      0.20    5.7825  
9      0.00   34.4700

**2. Atribut .tail()

Atribut .tail() untuk melihat 5(default dan bisa dirubah) data teratas pada dataframe.

In [18]:
data.tail()

Ship Mode   Segment        Country         City       State  \
9989    Second Class  Consumer  United States        Miami     Florida   
9990  Standard Class  Consumer  United States   Costa Mesa  California   
9991  Standard Class  Consumer  United States   Costa Mesa  California   
9992  Standard Class  Consumer  United States   Costa Mesa  California   
9993    Second Class  Consumer  United States  Westminster  California   

      Postal Code Region         Category Sub-Category    Sales  Quantity  \
9989        33180  South        Furniture  Furnishings   25.248         3   
9990        92627   West        Furniture  Furnishings   91.960         2   
9991        92627   West       Technology       Phones  258.576         2   
9992        92627   West  Office Supplies        Paper   29.600         4   
9993        92683   West  Office Supplies   Appliances  243.160         2   

      Discount   Profit  
9989       0.2   4.1028  
9990       0.0  15.6332  
9991       0.2  19.3932  
9992       0.0  13.3200  
9993       0.0  72.9480

**3. Atribut .info()**


Attribute .info() digunakan untuk mengecek kolom apa yang membentuk dataframe itu, data types, berapa yang non null, dll. Attribute ini tidak dapat digunakan pada series, hanya pada data frame saja.


In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Ship Mode     9994 non-null   object 
 1   Segment       9994 non-null   object 
 2   Country       9994 non-null   object 
 3   City          9994 non-null   object 
 4   State         9994 non-null   object 
 5   Postal Code   9994 non-null   int64  
 6   Region        9994 non-null   object 
 7   Category      9994 non-null   object 
 8   Sub-Category  9994 non-null   object 
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64  
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB


**4. Attribute .shape**

Attribute .shape digunakan untuk mengetahui berapa baris dan kolom, hasilnya dalam format tuple (baris, kolom).


In [20]:
data.shape

(9994, 13)

**5. Attribute .dtypes**

Attribute .dtypes digunakan untuk mengetahui tipe data di tiap kolom. Tipe data object: kombinasi untuk berbagai tipe data (number & text, etc).



In [21]:
data.dtypes

Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

**6. Attribute .astype(nama_tipe_data)**

Attribute .astype(nama_tipe_data) untuk convert tipe data berdasarkan tipe data seperti: **float, int, str, numpy.float, numpy.int** ataupun **numpy.datetime**.


In [8]:
df_str = data.astype("str")
df_str.head()

Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   

  Postal Code Region         Category Sub-Category     Sales Quantity  \
0       42420  South        Furniture    Bookcases    261.96        2   
1       42420  South        Furniture       Chairs    731.94        3   
2       90036   West  Office Supplies       Labels     14.62        2   
3       33311  South        Furniture       Tables  957.5775        5   
4       33311  South  Office Supplies      Storage    22.368        2   

  Discount    Profit  
0      0.0   41.9136  
1      0.0   219.582  
2      0.0    6.8714  
3     0.45  -383.031  
4      0.2    2.5164

In [9]:
df_str.dtypes

Ship Mode       object
Segment         object
Country         object
City            object
State           object
Postal Code     object
Region          object
Category        object
Sub-Category    object
Sales           object
Quantity        object
Discount        object
Profit          object
dtype: object

**7. Attribute .copy()**

Attribute .copy() digunakan melakukan duplikat, untuk disimpan di variable yang berbeda mungkin supaya tidak loading data lagi.


In [10]:
df_SS = data.copy()
df_SS

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

**8. Attribute .to_list()**

Attribute .to_list() digunakan untuk mengubah series menjadi list dan tidak dapat digunakan untuk dataframe.

In [13]:
print(number_series.to_list())

[1, 2, 3, 4, 5, 5]


**9. Attribute .unique()**

Attribute .unique() digunakan menghasilkan nilai unik dari suatu kolom, hasilnya dalam bentuk numpy array. Attribute ini hanya digunakan pada series saja.


In [14]:
print(number_series.unique())

[1 2 3 4 5]


**10. Attribute .index**

Attribute .index digunakan untuk mencari index/key dari Series atau Dataframe.

In [15]:
data.index

RangeIndex(start=0, stop=9994, step=1)

**11. Attribute .columns**

Attribute .columns digunakan untuk mengetahui apa saja kolom yang tersedia di dataframe tersebut (hanya digunakan untuk dataframe saja).


In [16]:
data.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

**12. Attribute .count()**

Attribute .count() untuk menghitung jumlah data pada masing-masing kolom.


In [17]:
data.count()

Ship Mode       9994
Segment         9994
Country         9994
City            9994
State           9994
Postal Code     9994
Region          9994
Category        9994
Sub-Category    9994
Sales           9994
Quantity        9994
Discount        9994
Profit          9994
dtype: int64

**13. Attribute .value_counts()**

Attribute .value_counts() digunakan untuk mengetahui jumlah data kategori unik pada setiap kolom


In [21]:
data1.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

In [22]:
data1.Sentiment.value_counts()

negative    450
positive    450
Name: Sentiment, dtype: int64

**14. Attribute .describe()**

Attribute .describe() digunakan untuk menampilkan ringkasan statistik data numerik pada sebuah dataframe


In [23]:
data.describe()

Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

#**2. OPERASI NUMPY DAN MATRIKS**

###**Numpy**

NumPy merupakan salah satu library Python yang banyak digunakan dalam proses analisis data karena turnya yang hebat


In [2]:
# Import modul
import numpy as np

###Membuat Array Numpy

Membuat Array menggunakan Numpy dengan List dan diubah menjadi numpy array

In [25]:
# Membuat Array numpy
list = [1,2,3,4,5,6,7,8,9,10]
arr_list = np.array([list])
arr_list

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

**Beberapa fungsi yang dapat digunakan dalam membuat array**

```
zeros()    -> Membuat array dengan nilai 0
ones()     -> Membuat array dengan nilai 1
arange()   -> Membuat array dengan nilai dalam range
linspace() -> Membuat array dengan nilai dalam interval
logspace() -> Membuat array dengan nilai log Base10 dalam interval
full       -> Membuat array dengan semua elemen penyusunnya sama
full_like  -> Membuat array dengan semua elemen penyusunnya sama namun ukurannya dari array lainnya
identity   -> Membuat array matriks identitas
repeat     -> Membuat array dengan perulangan array atau sequence

```

In [26]:
# Fungsi didalam numpy
# membuat array dengan nilai 0 dengan shape (5,5)
#zeros() -> nilai 0
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
#membuat array dengan nilai 1 dengan shape (5,5)
#ones() -> nilai 1
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
#arange() -> (start, stop, step/loncat berapa)
print(np.arange(6, 20, 4))

[ 6 10 14 18]


In [29]:
#linspace() -> (start, stop, number)
print(np.linspace(1, 10, 4))

[ 1.  4.  7. 10.]


In [30]:
#logspace() -> (start, stop, number)
print(np.logspace(1, 10, 2))

[1.e+01 1.e+10]


In [31]:
#full()
print(np.full((2,5), 4))

[[4 4 4 4 4]
 [4 4 4 4 4]]


In [35]:
#full_like()
# Membuat array matriks dengan shape yang sama dengan A dengan semua elemennya 4

A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 3))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [37]:
# Random decimal numbers
print(np.random.rand(5,3))


[[0.26450852 0.29365531 0.04449146]
 [0.77866809 0.36273554 0.86631511]
 [0.0439613  0.90034227 0.91195107]
 [0.30657415 0.20199321 0.77708656]
 [0.9805141  0.61677429 0.77066842]]


In [36]:
#random() -> jika di run hasil nya akan beda2 karena random
print(np.random.randint(-4,8, size = (3,3)))

[[ 6 -3  7]
 [-1  5  3]
 [ 6  5  0]]


In [38]:
#identity()
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [39]:
#repeat() -> Membuat matriks dengan perulangan array(kolom),
#axis = 0 (perulangan baris)
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
#repeat() -> Membuat matriks dengan perulangan array(kolom),
#axis = 1 (perulangan kolom)
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis = 1)
print(r1)

[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]]


###Metode-metode pada Array

Objek array pada Python Numpy memiliki berbagai method untuk melakukan operasi atau perintah-perintah tertentu. Berikut adalah fungsi-fungsi yang merupakan metode pada array yang sering dipakai:

**1. array.ndim**

Metode ini digunakan untuk mengetahui dimensi dari array.


In [41]:
#mengetahui dimensi array
A = np.array([1,2,3,4,5,6,7,8,9,10], dtype = 'int32')
print(A)

print("Dimnsi array A : ", A.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
Dimnsi array A :  1


**2. array.shape**

Metode ini digunakan untuk mengetahui ukuran (variabel dan baris) dari array.


In [44]:
#mengetahui ukuran array
B = np.array([[1.0,2.0,3.0,4.0,5.0],[6,7,8,9,10]])
print(B)

print("Ukuran Shape dari array B : ", B.shape)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Ukuran Shape dari array B :  (2, 5)


**3. array.dtype**

Metode ini digunakan untuk mengetahui type data dari elemen penyusun array.


In [45]:
A.dtype

dtype('int32')

**3. array.size**

Metode ini digunakan untuk menghitung jumlah elemen dari array.

In [46]:
A.size

10

###Multidimensional Array

Salah satu tur menarik dari NumPy adalah dia mampu membuat multidimensional array dan melakukan manipulasi array dengan mudah dan cepat.

Multidimensional array adalah array yang berbentuk lebih dari 1 dimensi (1D), bisa 2D, 3D, 4D dan seterusnya.

Cara membuat multidimensional array sama dengan membuat array 1 dimensi, perbedaannya hanya pada parameter yang digunakan.

Berikut contohnya membuat array 2 dimensi :

In [47]:
arrku = np.array([[1,2,3,4,5], [2,4,6,8,10]])
arrku


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

Array diatas adalah berbentuk (2,5) artinya mempunyai 2 baris dan 5 kolom Kita bisa melihat jumlah elemen di setiap dimensi dengan menggunakan shape


In [48]:
arrku.shape


(2, 5)

###Indexing dan Slicing

Kita juga dapat melakukan indexing dan slicing terhadap array dengan mudah.
Indexing dimulai dari 0 dan dimulai dengan notasi bracket “[ ]”

Misal kita ingin mencari nilai yang berada di index 0, 2, dan 4

In [49]:
arrku1 = np.array([1,2,3,4,5])
print(arrku1[0])
print(arrku1[2])
print(arrku1[4])


1
3
5


Untuk mengambil nilai berderet tambahkan “:”

In [3]:
arrku1 = np.array([1,2,3,4,5])
print(arrku1[0:4])

[1 2 3 4]


In [4]:
arrku2 = np.array([[1,2,3,4,5], [2,4,6,8,10]])
print(arrku2)
print(arrku2[1,3])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
8


Nilai pada kolom index ke-1 dan baris index ke-1 adalah 4


In [5]:
#coba
C = np.array([1,2,3,4,5,6,7,8,9,10])
print(C[0])
print(C[0:5])

1
[1 2 3 4 5]


In [6]:
D = np.array([[1,2,3,4,5], [2,4,5,6,7]])
print(D)
print(D[4:5])

[[1 2 3 4 5]
 [2 4 5 6 7]]
[]


###**Operasi Aritmatika**

 Operasi aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian dan perpangkatan.

 Operator yang digunakan adalah `+`, `-`, `/` dan `*`

 Berikut contoh operasi aritmatika pada array

In [8]:
arrshin = np.array([1,2,3,4,5])
arrtya = np.array([2,2,2,2,2])
print("Penjumlahan   = ", arrshin + arrtya)
print("Pengurangan   = ", arrshin - arrtya)
print("Perkalian     = ", arrshin * arrtya)
print("Pembagian     = ", arrshin / arrtya)
print("Perpangkatan  = ", arrshin ** arrtya)


Penjumlahan   =  [3 4 5 6 7]
Pengurangan   =  [-1  0  1  2  3]
Perkalian     =  [ 2  4  6  8 10]
Pembagian     =  [0.5 1.  1.5 2.  2.5]
Perpangkatan  =  [ 1  4  9 16 25]


###Operasi Matematika

NumPy mempunyai fungsi matematika yang dapat digunakan pada Array.

Beberapa contoh fungsi statistik antara lain min(), max(), mean(), sum(), std()

In [9]:
arrku3 = np.array([1,-2,3,4,5])
print("Nilai minimal   = ", arrku3.min())
print("Nilai maksimal  = ", arrku3.max())
print("Nilai rata-rata = ", arrku3.mean())
print("Total nilai     = ", arrku3.sum())
print("Standar Deviasi = ", arrku3.std())


Nilai minimal   =  -2
Nilai maksimal  =  5
Nilai rata-rata =  2.2
Total nilai     =  11
Standar Deviasi =  2.4819347291981715


Ada juga fungsi argmin() dan argmax() untuk mendapatkan index dari nilai minimum dan maksimum


In [10]:
print("Index nilai niminal = ", arrku3.argmin())
print("Index nilai maksimal = ", arrku3.argmax())

Index nilai niminal =  1
Index nilai maksimal =  4


###Transformasi Array

Kita dapat membuat array baru dari array yang sudah ada melalui berbagai metode transformasi seperti merubah ukuran, menggabungkan dua array atau lebih dan lain sebagainya.

**1. array.reshape**
Metode ini digunakan untuk merubah shape array dengan jumlah elemen yang tidak berubah.


In [12]:
awal = np.array([[1,2,3,4],[5,6,7,8]])
print(awal)
akhir = awal.reshape((8,1))
print(akhir)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


Perhatikan bahwa array sebelum memiliki jumlah elemen 8 (2,4) dan array sesudah juga memiliki jumlah elemen 8 (4,2).


**2. array.vstack**

Metode ini dilakukan untuk menumpuk beberapa array secara vertikal


In [13]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

**3. array.hstack**

Metode ini dilakukan untuk menumpuk beberapa array secara horizontal.


In [14]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
print(np.hstack((h1,h2)))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


###**Representasi Matriks Pada Python**

Matriks adalah array 2 dimensi khusus yang mempertahankan sifat 2 dimensinnya melalui operasi. Matriks memiliki operator khusus tertentu, seperti perkalian matriks dan pemangkatan matriks.

Berikut adalah beberapa penulisan python di berbagai platform:


In [15]:
import numpy as np

A = np.array([[1, 2], [4, 5]])
A


array([[1, 2],
       [4, 5]])

In [16]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###**Operasi Matriks Pada Python**

In [17]:
P = np.array([[1, 2], [4, 5]])
P


array([[1, 2],
       [4, 5]])

In [18]:
Q = np.array([[7, 8], [9, 10]])
Q


array([[ 7,  8],
       [ 9, 10]])

In [19]:
a=29
a

29

**Penjumlahan Matriks**

In [20]:
np.add(P,Q)

array([[ 8, 10],
       [13, 15]])

**Pengurangan Matriks**

In [21]:
np.subtract(P,Q)


array([[-6, -6],
       [-5, -5]])

**Perkalian Skalar Matriks**

In [22]:
a*P

array([[ 29,  58],
       [116, 145]])

**Perkalian Matriks**

In [23]:
np.multiply(P,Q)

array([[ 7, 16],
       [36, 50]])

**Perkalian Titik Matriks (Dot Product)**

In [24]:
np.dot(P,Q)


array([[25, 28],
       [73, 82]])

**Transpose Matriks**

In [25]:
P.T

array([[1, 4],
       [2, 5]])

**Operasi Fungsi Pada Setiap Elemen Matriks - Akar Kuadrat**


In [26]:
np.sqrt(P)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

**Menjumlahkan Semua Elemen Kolom Sebuah Matriks**

In [27]:
Q

array([[ 7,  8],
       [ 9, 10]])

In [28]:
np.sum(Q,axis=1)


array([15, 19])

**Menjumlahkan Semua Elemen Baris Sebuah Matriks**

In [29]:
np.sum(Q,axis=0)

array([16, 18])

###**Aljabar Linear Pada Python**

Dalam modul numpy juga disediakan fungsi-fungsi Aljabar Linear untuk matriks. Beberapa konsep Aljabar Linear yang akan ditunjukkan di modul ini adalah
* Determinan

* Inverse

* Nilai eigen

* Vector eigen
* Matriks identitas
* Matriks satuan
* Matriks nol
* Matriks segitiga L dan U
* Dekomposisi L U matriks

In [2]:
import numpy as np

In [3]:
A = np.array([[2,3,4],[7, 8, 9],[10, 7, 8]])
A


array([[ 2,  3,  4],
       [ 7,  8,  9],
       [10,  7,  8]])

In [4]:
B = np.array([[5,7,4],[6, 8, 9],[1, 2, 6]])
B


array([[5, 7, 4],
       [6, 8, 9],
       [1, 2, 6]])

**Determinan**

In [5]:
np.linalg.det(A)


-20.000000000000007

**Inverse Matriks**

In [6]:
np.linalg.inv(A)


array([[-0.05, -0.2 ,  0.25],
       [-1.7 ,  1.2 , -0.5 ],
       [ 1.55, -0.8 ,  0.25]])

**Nilai Eigen dan Vector Eigen**

In [7]:
eig, vec_eig = np.linalg.eig(A)
print('Nilai eigen matriks A:')
print(eig)
print('Vektor eigen matriks A:')
print(vec_eig)


Nilai eigen matriks A:
[19.39079317 -1.9262474   0.53545423]
Vektor eigen matriks A:
[[-0.27295093 -0.54761756  0.15754422]
 [-0.6940728  -0.31621014 -0.8168342 ]
 [-0.66615369  0.7746781   0.55494297]]


**Matriks Identitas**

In [8]:
Identitas=np.identity(5)
print(Identitas)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
Identitas[:,3]

array([0., 0., 0., 1., 0.])

**Matriks Satuan**

In [10]:
Satuan=np.ones((2,3))
Satuan


array([[1., 1., 1.],
       [1., 1., 1.]])

**Matriks Nol**

In [11]:
MatriksNol=np.zeros(10)
MatriksNol


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Matriks Segitiga Atas dan Bawah**

In [12]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
M


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
Lower=np.tril(M, -1)
Lower


array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [14]:
Upper=np.triu(M, 1)
Upper

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

#**LATIHAN**

1. Buatlah array matriks identitas dengan ukuran 20x20! Latihan


In [15]:
Identitas=np.identity(20)
print(Identitas)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

2. Buatlah array matriks dengan ukuran sesuai dengan array c dan dengan elemennya adalah bilangan 112!


In [16]:
c=[80, 10, 40, 90, 100, 55]
c = np.array([80, 10, 40, 90, 100, 55])
print(c)
print(np.full_like(c,112))


[ 80  10  40  90 100  55]
[112 112 112 112 112 112]
